name: Deploy

on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3

      - name: Deploy
        run: echo 'DEPLOY NEW VERSION!'
